require('dotenv').config();
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');

// ── Config จาก Environment Variables ─────────────────────────────────────────
const XRAY_CLIENT_ID     = process.env.XRAY_CLIENT_ID;
const XRAY_CLIENT_SECRET = process.env.XRAY_CLIENT_SECRET;
const JIRA_PROJECT_KEY   = process.env.JIRA_PROJECT_KEY;
const JIRA_BASE_URL      = process.env.JIRA_BASE_URL;      // เช่น https://yourcompany.atlassian.net
const JIRA_EMAIL         = process.env.JIRA_EMAIL;
const JIRA_API_TOKEN     = process.env.JIRA_API_TOKEN;
const XRAY_TEST_PLAN_KEY = process.env.XRAY_TEST_PLAN_KEY; // optional เช่น PROJ-123

// ── Validate ──────────────────────────────────────────────────────────────────
const required = { XRAY_CLIENT_ID, XRAY_CLIENT_SECRET, JIRA_PROJECT_KEY, JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN };
const missing = Object.entries(required).filter(([, v]) => !v).map(([k]) => k);
if (missing.length > 0) {
  console.error('❌ Missing environment variables:', missing.join(', '));
  console.error('\nกรุณาตั้งค่าใน .env หรือ export ก่อนรัน');
  process.exit(1);
}

// ── HTTP Helper ───────────────────────────────────────────────────────────────
function request(options, body) {
  return new Promise((resolve, reject) => {
    const mod = options.protocol === 'http:' ? http : https;
    const req = mod.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve({ status: res.statusCode, body: JSON.parse(data) }); }
        catch { resolve({ status: res.statusCode, body: data }); }
      });
    });
    req.on('error', reject);
    if (body) req.write(typeof body === 'string' ? body : JSON.stringify(body));
    req.end();
  });
}

// ── Step 1: ขอ Xray Token ─────────────────────────────────────────────────────
async function getXrayToken() {
  console.log('🔑 Getting Xray token...');
  const res = await request({
    hostname: 'xray.cloud.getxray.app',
    path: '/api/v2/authenticate',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    protocol: 'https:',
  }, { client_id: XRAY_CLIENT_ID, client_secret: XRAY_CLIENT_SECRET });

  if (res.status !== 200) throw new Error(`Xray auth failed: ${JSON.stringify(res.body)}`);
  const token = typeof res.body === 'string' ? res.body.replace(/"/g, '') : res.body;
  console.log('✅ Xray token received');
  return token;
}

// ── Step 2: Upload JUnit XML → Xray (Test Execution) ─────────────────────────
async function uploadJUnitToXray(token) {
  const xmlPath = path.join('xray-results', 'results.xml');
  if (!fs.existsSync(xmlPath)) {
    console.warn('⚠️  No JUnit XML found at', xmlPath, '- skipping Test Execution upload');
    return null;
  }

  const xml = fs.readFileSync(xmlPath, 'utf8');
  let queryPath = `/api/v2/import/execution/junit?projectKey=${JIRA_PROJECT_KEY}`;
  if (XRAY_TEST_PLAN_KEY) queryPath += `&testPlanKey=${XRAY_TEST_PLAN_KEY}`;

  console.log('📤 Uploading JUnit XML to Xray...');
  const res = await request({
    hostname: 'xray.cloud.getxray.app',
    path: queryPath,
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'text/xml',
      'Content-Length': Buffer.byteLength(xml),
    },
    protocol: 'https:',
  }, xml);

  if (res.status !== 200) throw new Error(`JUnit upload failed (${res.status}): ${JSON.stringify(res.body)}`);
  console.log('✅ Test Execution created:', res.body.key || res.body);
  return res.body.key;
}

// ── Step 3: สร้าง Jira Issue สำหรับแนบไฟล์ (ถ้ายังไม่มี) ─────────────────────
async function createOrFindJiraIssue(executionKey) {
  // ถ้ามี execution key แล้ว ใช้อันนั้นเลย
  if (executionKey) return executionKey;

  // สร้าง Task issue ใหม่สำหรับแนบผลลัพธ์
  console.log('📝 Creating Jira issue for attachments...');
  const jiraAuth = Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString('base64');
  const jiraHost = new URL(JIRA_BASE_URL).hostname;

  const res = await request({
    hostname: jiraHost,
    path: '/rest/api/3/issue',
    method: 'POST',
    headers: {
      'Authorization': `Basic ${jiraAuth}`,
      'Content-Type': 'application/json',
    },
    protocol: 'https:',
  }, {
    fields: {
      project: { key: JIRA_PROJECT_KEY },
      summary: `[Playwright] API Search Results - ${new Date().toISOString().split('T')[0]}`,
      issuetype: { name: 'Task' },
      description: {
        type: 'doc', version: 1,
        content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Auto-generated by Playwright test. ดูไฟล์แนบสำหรับผลลัพธ์ Item IDs และ content_type' }] }]
      }
    }
  });

  if (res.status !== 201) throw new Error(`Create issue failed (${res.status}): ${JSON.stringify(res.body)}`);
  console.log('✅ Created Jira issue:', res.body.key);
  return res.body.key;
}

// ── Step 4: แนบไฟล์ CSV/JSON ใน Jira Issue ───────────────────────────────────
async function attachFilesToJira(issueKey) {
  const resultsDir = 'results';
  if (!fs.existsSync(resultsDir)) {
    console.warn('⚠️  No results/ folder found - skipping attachments');
    return;
  }

  const files = fs.readdirSync(resultsDir).filter(f => f.endsWith('.csv') || f.endsWith('.json'));
  if (files.length === 0) {
    console.warn('⚠️  No CSV/JSON files found in results/');
    return;
  }

  const jiraAuth = Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString('base64');
  const jiraHost = new URL(JIRA_BASE_URL).hostname;

  for (const file of files) {
    const filePath = path.join(resultsDir, file);
    const fileContent = fs.readFileSync(filePath);
    const boundary = '----FormBoundary' + Math.random().toString(36).slice(2);

    const body = Buffer.concat([
      Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${file}"\r\nContent-Type: application/octet-stream\r\n\r\n`),
      fileContent,
      Buffer.from(`\r\n--${boundary}--\r\n`),
    ]);

    console.log(`📎 Attaching ${file} to ${issueKey}...`);
    const res = await request({
      hostname: jiraHost,
      path: `/rest/api/3/issue/${issueKey}/attachments`,
      method: 'POST',
      headers: {
        'Authorization': `Basic ${jiraAuth}`,
        'X-Atlassian-Token': 'no-check',
        'Content-Type': `multipart/form-data; boundary=${boundary}`,
        'Content-Length': body.length,
      },
      protocol: 'https:',
    }, body.toString('binary'));

    if (res.status !== 200) {
      console.error(`  ❌ Failed to attach ${file}: ${res.status}`);
    } else {
      console.log(`  ✅ Attached: ${file}`);
    }
  }
}

// ── Step 5: สรุปผลและแสดง link ───────────────────────────────────────────────
function printSummary(executionKey, issueKey) {
  console.log('\n' + '='.repeat(60));
  console.log('🎉 Upload complete!');
  console.log('='.repeat(60));
  if (executionKey) {
    console.log(`\n📊 Test Execution (Pass/Fail):`);
    console.log(`   ${JIRA_BASE_URL}/browse/${executionKey}`);
  }
  if (issueKey) {
    console.log(`\n📎 Attachments (CSV/JSON):`);
    console.log(`   ${JIRA_BASE_URL}/browse/${issueKey}`);
  }
  console.log('');
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  try {
    const token = await getXrayToken();
    const executionKey = await uploadJUnitToXray(token);
    const issueKey = await createOrFindJiraIssue(executionKey);
    await attachFilesToJira(issueKey || executionKey);
    printSummary(executionKey, issueKey || executionKey);
  } catch (err) {
    console.error('\n❌ Error:', err.message);
    process.exit(1);
  }
}

main();
